
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: menu_bioin_development


test:
  <<: *default
  database: menu_bioin_test

production:
  <<: *default
  database: menu_bioin_production
  username: menu_bioin
  password: <%= ENV['MENU_BIOIN_DATABASE_PASSWORD'] %>



 #default: &default
  #adapter: mysql2
  #encoding: utf8mb4
  #pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #username: menu
  #password: hola
  #database: menubioin
  #socket: /var/run/mysqld/mysqld.sock

#development:
  #<<: default

#test:
  #<<:default

#production:
 # <<: *default
