default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bioindev
  password: BioinDev123asd
  database: menubioin
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
